### PR TITLE
Add support for showing modal in edit vs create interval

### PR DESCRIPTION
**Pull request by johnmryan**
Hey there @birik! Thanks for this awesome module!

Our application would like to only show the modal for deleting intervals, and create interval would just automatically book the slot.

Not particularly happy with my implementation =/, but I tried to do it in a non-breaking change. Would appreciate any feedback if you have opinions on this. 

If the approach looks reasonable to you, I will add corresponding tests (it passes the existing tests).

**Note:** I will also update the documentation and can add in an example of usage, just wanted to make sure we agree on an implementation first.

### CODE REVIEW

**Comment by birik** [comment]
Hi @johnmryan 

Thank you for your commit. I think this is great idea to have this option. Can you implement a little bit another way:
- don't change the current property useModule
- add new property like showModuleCase (you can use other name). This property will accept the array of enum and default value is ["create", "edit"]. Based on the cases you can react.
- Also, it will be great, if these "cases" will send to the module as prop that it will be possible to show different content in the module. Can you implement like this?

What do you think about this solution? Is it valid for you?

Best regards,
Evgeny

**Comment by johnmryan** [comment]
Will do! I'll take some time to think about the naming for `showModuleCase`. 

I should have an updated PR with the suggested changes by the weekend. Thanks!

**Comment by johnmryan** [comment]
@birik -- quick question, wanted some feedback.

If a user says:
```
useModal={false}
showModalCase=['create']
```

Should we hide the modal in this case, because they set `useModal` to false?

Might be helpful to consider the following examples:

```
useModal={true}
showModalCase=['edit'] // this will show modal for edit only?
```

```
useModal={false}
showModalCase=['edit', 'create'] // this will never show modal, since useModal is false
```

Thanks in advance!

**Comment by johnmryan** [comment]
If you agree that `useModal: false` should always hide the modal, can you give my code a quick look? That is the way I chose to implement it.

**Comment by birik** [comment]
@johnmryan Thanks for your commit. I will make small cange and publish to npm

**Comment by birik** [comment]
@johnmryan The new version (0.1.3) with showModalCase was published to npm.

**Pull request merged**
